### ISSUE TITLE
Downtime is not reported, Update the workflow files

### ISSUE THREAD

**Issue by jayantkatia** [canonical-web-and-design/upptime#106]
**Describe the bug**
Downtime (https://github.com/canonical-web-and-design/upptime/commit/a1b14a6fc0ab1e93fd6cb9f5573c9bcbe9f795bc) is not reported and published as an issue.

**Possible Resolution**
Update the workflow files to use the latest version of Uptime-monitor.
 https://github.com/upptime/upptime/issues/393#issuecomment-873563720

**Comment by tbille** [comment]
Updated.
Thanks for the tip @jayantkatia :smile:
